plugins:
  - jekyll-toc
  - jekyll-last-modified-at
  - jekyll-contentblocks

baseurl: /cv

toc:
  min_level: 2
  max_level: 5

last-modified-at:
  date-format: '%d-%m-%y'

cv:
  accent-color: '#bc412b'
  languages: ['it', 'en']
